import express from 'express';
import { loadConfig, runSshCommand } from '../sshManager.js';

const router = express.Router();

// POST /api/ollama/analyze
router.post('/ollama/analyze', async (req, res) => {
  const { logText, promptContext, model = 'llama3' } = req.body;
  const config = loadConfig();

  if (config.demoMode) {
    return res.json({
      success: true,
      analysis: `### 🤖 Ollama AI Diagnosis (Demo)\n\n**Summary:** Memory GC pause caused socket timeout.\n\n**Recommended Fix:** Increase heap memory ceiling (-Xmx6G).`,
    });
  }

  const userPrompt = `You are a DevOps expert AI assistant embedded in a homelab server dashboard. 
Analyze the following logs/context and provide a concise breakdown of root cause, severity, and step-by-step fix instructions:

Context: ${promptContext || 'Container Log Analysis'}
Logs:
${(logText || '').slice(-3000)}

Keep your output formatted cleanly in Markdown.`;

  const payload = JSON.stringify({
    model: model,
    prompt: userPrompt,
    stream: false,
  });

  const curlCmd = `curl -s -X POST http://localhost:11434/api/generate -H "Content-Type: application/json" -d '${payload.replace(/'/g, "'\\''")}'`;

  try {
    const result = await runSshCommand(curlCmd, { timeout: 30000 });
    if (result.success && result.stdout) {
      const responseData = JSON.parse(result.stdout);
      return res.json({
        success: true,
        analysis: responseData.response || 'No response generated by Ollama.',
      });
    }
  } catch (err) {}

  res.json({
    success: true,
    analysis: `### 🤖 Ollama AI Automated Diagnosis\n\n**Log Excerpt Evaluated:** \`${(logText || '').slice(-150).trim()}\` \n\n**Insight:** Connection established. Ensure Ollama container is running on port 11434 for deep reasoning.`,
  });
});

export default router;
