import { loadConfig, saveConfig, runSshCommand } from '../sshManager.js';

export function getRecommendedJavaVersion(mcVersion) {
  if (!mcVersion) return 'java21';
  const v = mcVersion.trim();

  if (v.startsWith('26.') || v.toUpperCase() === 'LATEST') {
    return 'java25';
  }

  const match = v.match(/^1\.(\d+)(?:\.(\d+))?/);
  if (match) {
    const minor = parseInt(match[1], 10);
    const patch = parseInt(match[2] || '0', 10);

    if (minor >= 21) return 'java21';
    if (minor === 20 && patch >= 5) return 'java21';
    if (minor >= 18) return 'java17';
    if (minor === 17) return 'java17';
    if (minor >= 13) return 'java11';
    return 'java8';
  }

  return 'java21';
}

export function parseProperties(content) {
  const props = {};
  const lines = content.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#') && trimmed.includes('=')) {
      const idx = trimmed.indexOf('=');
      const key = trimmed.slice(0, idx).trim();
      const val = trimmed.slice(idx + 1).trim();
      props[key] = val;
    }
  }
  return props;
}

export function serializeProperties(props) {
  let output = '# Minecraft server properties generated by Server-Dash\n';
  output += `# ${new Date().toISOString()}\n\n`;
  for (const [k, v] of Object.entries(props)) {
    output += `${k}=${v}\n`;
  }
  return output;
}

export async function getMinecraftServers() {
  const config = loadConfig();
  if (config.demoMode) {
    return [
      {
        name: 'minecraft',
        port: '25565',
        status: 'Up',
        state: 'running',
        type: 'PAPER',
        version: 'LATEST',
        memory: '4G',
        mode: 'survival',
        difficulty: 'normal',
        motd: 'Main Paper Vanilla SMP Server',
      },
    ];
  }

  const result = await runSshCommand(
    `docker ps -a --format 'name={{.Names}}|status={{.Status}}|ports={{.Ports}}|image={{.Image}}' | grep -iE "minecraft|itzg|mc" || echo ""`
  );

  if (!result.success || !result.stdout) return [];

  const lines = result.stdout.split('\n').filter((l) => l.trim().length > 0);
  const servers = [];

  for (const line of lines) {
    const parts = line.split('|').reduce((acc, curr) => {
      const [k, ...v] = curr.split('=');
      acc[k] = v.join('=');
      return acc;
    }, {});

    const name = parts.name || 'minecraft';
    const envRes = await runSshCommand(
      `docker inspect ${name} --format '{{json .Config.Env}}' 2>/dev/null || echo "[]"`
    );

    let envList = [];
    try {
      if (envRes.success && envRes.stdout) {
        envList = JSON.parse(envRes.stdout);
      }
    } catch (e) {}

    const envMap = {};
    envList.forEach((e) => {
      const idx = e.indexOf('=');
      if (idx > -1) {
        envMap[e.slice(0, idx)] = e.slice(idx + 1);
      }
    });

    const portMatch = (parts.ports || '').match(/0\.0\.0\.0:(\d+)->25565/);
    const port = portMatch ? portMatch[1] : '25565';

    servers.push({
      name,
      port,
      status: parts.status || 'Unknown',
      state: parts.status && parts.status.toLowerCase().includes('up') ? 'running' : 'exited',
      image: parts.image || 'itzg/minecraft-server',
      type: envMap.TYPE || 'PAPER',
      version: envMap.VERSION || 'LATEST',
      memory: envMap.MEMORY || '4G',
      mode: envMap.MODE || 'survival',
      difficulty: envMap.DIFFICULTY || 'normal',
      motd: envMap.MOTD || 'Minecraft Server',
      modpackUrl: envMap.MODPACK || '',
      mods: envMap.MODS || '',
    });
  }

  return servers;
}

export async function createMinecraftServer(params) {
  const {
    name = 'minecraft',
    port = 25565,
    type = 'PAPER',
    version = '1.20.4',
    javaVersion,
    memory = '4G',
    mode = 'survival',
    difficulty = 'normal',
    motd = 'A Minecraft Server',
    maxPlayers = 20,
    modpackUrl = '',
    mods = '',
  } = params;

  const config = loadConfig();
  const cleanName = name.trim().toLowerCase().replace(/[^a-z0-9-]/g, '-');
  const actualJava = javaVersion || getRecommendedJavaVersion(version);
  const imageTag = actualJava ? `itzg/minecraft-server:${actualJava}` : 'itzg/minecraft-server:latest';

  let dockerCmd = `docker run -d --name ${cleanName} \\
  -e EULA=TRUE \\
  -e TYPE=${type.toUpperCase()} \\
  -e VERSION=${version} \\
  -e MEMORY=${memory} \\
  -e MODE=${mode} \\
  -e DIFFICULTY=${difficulty} \\
  -e MOTD="${motd.replace(/"/g, '\\"')}" \\
  -e MAX_PLAYERS=${maxPlayers} \\
  -p ${port}:25565 \\
  -v ${cleanName}_data:/data \\
  --restart unless-stopped`;

  if (modpackUrl && modpackUrl.trim()) {
    dockerCmd += ` \\\n  -e MODPACK="${modpackUrl.trim()}"`;
  }
  if (mods && mods.trim()) {
    dockerCmd += ` \\\n  -e MODS="${mods.trim()}"`;
  }
  dockerCmd += ` \\\n  ${imageTag}`;

  const result = await runSshCommand(dockerCmd, { timeout: 30 });

  if (!config.services.some((s) => s.containerName === cleanName)) {
    config.services.push({
      id: cleanName,
      name: `Minecraft (${cleanName})`,
      category: 'Gaming',
      containerName: cleanName,
      port: parseInt(port, 10),
      protocol: 'tcp',
      healthPath: '',
      uiPath: '',
      btnLabel: 'Server Address',
      icon: 'Gamepad2',
      description: `${type} Minecraft Server on port ${port}`,
    });
    saveConfig(config);
  }

  return {
    success: result.success,
    server: { name: cleanName, port, type, version, memory },
    output: result.stdout || result.stderr,
    error: result.error,
  };
}
